/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import static Codigo.Intranet.asigAl;
import static Codigo.Intranet.asigDat;
import static Codigo.Intranet.contAsig;
import static Codigo.Intranet.posAsig;
import static Codigo.Intranet.posAsigal;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author PC
 */
public class Malla extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Datos
     */
    public Malla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCalI = new javax.swing.JButton();
        btnAlgI = new javax.swing.JButton();
        btnProg = new javax.swing.JButton();
        btnQmc = new javax.swing.JButton();
        btnCalII = new javax.swing.JButton();
        btnAlgII = new javax.swing.JButton();
        btnProgAv = new javax.swing.JButton();
        btnFsc = new javax.swing.JButton();
        btnMatDis = new javax.swing.JButton();
        btnSisOp = new javax.swing.JButton();
        btnCirElc = new javax.swing.JButton();
        btnEcDif = new javax.swing.JButton();
        btnElec = new javax.swing.JButton();
        btnEst = new javax.swing.JButton();
        btnProgObj = new javax.swing.JButton();
        btnSisDig = new javax.swing.JButton();
        lblAp = new javax.swing.JLabel();
        lblRp = new javax.swing.JLabel();
        lblCrs = new javax.swing.JLabel();
        lblNocurs = new javax.swing.JLabel();
        lblSemII = new javax.swing.JLabel();
        lblSemI = new javax.swing.JLabel();
        lblSemIII = new javax.swing.JLabel();
        lblSemIV = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Malla");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)), "Malla", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 24))); // NOI18N

        btnCalI.addActionListener(this);
        btnCalI.setBackground(new java.awt.Color(0, 0, 0));
        btnCalI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalI.setForeground(new java.awt.Color(255, 255, 0));
        btnCalI.setText("Calculo I");

        btnAlgI.addActionListener(this);
        btnAlgI.setBackground(new java.awt.Color(0, 0, 0));
        btnAlgI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAlgI.setForeground(new java.awt.Color(255, 255, 0));
        btnAlgI.setText("Algebra I");

        btnProg.addActionListener(this);
        btnProg.setBackground(new java.awt.Color(0, 0, 0));
        btnProg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnProg.setForeground(new java.awt.Color(255, 255, 0));
        btnProg.setText("Programacion");

        btnQmc.addActionListener(this);
        btnQmc.setBackground(new java.awt.Color(0, 0, 0));
        btnQmc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnQmc.setForeground(new java.awt.Color(255, 255, 0));
        btnQmc.setText("Quimica");

        btnCalII.addActionListener(this);
        btnCalII.setBackground(new java.awt.Color(0, 0, 0));
        btnCalII.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalII.setForeground(new java.awt.Color(255, 255, 0));
        btnCalII.setText("Calculo II");

        btnAlgII.addActionListener(this);
        btnAlgII.setBackground(new java.awt.Color(0, 0, 0));
        btnAlgII.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAlgII.setForeground(new java.awt.Color(255, 255, 0));
        btnAlgII.setText("Algebra II");

        btnProgAv.addActionListener(this);
        btnProgAv.setBackground(new java.awt.Color(0, 0, 0));
        btnProgAv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnProgAv.setForeground(new java.awt.Color(255, 255, 0));
        btnProgAv.setText("Program. Avanzada");

        btnFsc.addActionListener(this);
        btnFsc.setBackground(new java.awt.Color(0, 0, 0));
        btnFsc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFsc.setForeground(new java.awt.Color(255, 255, 0));
        btnFsc.setText("Fisica");

        btnMatDis.addActionListener(this);
        btnMatDis.setBackground(new java.awt.Color(0, 0, 0));
        btnMatDis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMatDis.setForeground(new java.awt.Color(255, 255, 0));
        btnMatDis.setText("Matematicas Discretas");

        btnSisOp.addActionListener(this);
        btnSisOp.setBackground(new java.awt.Color(0, 0, 0));
        btnSisOp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSisOp.setForeground(new java.awt.Color(255, 255, 0));
        btnSisOp.setText("Sistemas Operativos");

        btnCirElc.addActionListener(this);
        btnCirElc.setBackground(new java.awt.Color(0, 0, 0));
        btnCirElc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCirElc.setForeground(new java.awt.Color(255, 255, 0));
        btnCirElc.setText("Circuitos Electricos");

        btnEcDif.addActionListener(this);
        btnEcDif.setBackground(new java.awt.Color(0, 0, 0));
        btnEcDif.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEcDif.setForeground(new java.awt.Color(255, 255, 0));
        btnEcDif.setText("Ecuaciones Diferenciales");

        btnElec.addActionListener(this);
        btnElec.setBackground(new java.awt.Color(0, 0, 0));
        btnElec.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnElec.setForeground(new java.awt.Color(255, 255, 0));
        btnElec.setText("Electromagnetismo");

        btnEst.addActionListener(this);
        btnEst.setBackground(new java.awt.Color(0, 0, 0));
        btnEst.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEst.setForeground(new java.awt.Color(255, 255, 0));
        btnEst.setText("Estadisticas");

        btnProgObj.addActionListener(this);
        btnProgObj.setBackground(new java.awt.Color(0, 0, 0));
        btnProgObj.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnProgObj.setForeground(new java.awt.Color(255, 255, 0));
        btnProgObj.setText("Prog. Orientada a Objetos");

        btnSisDig.addActionListener(this);
        btnSisDig.setBackground(new java.awt.Color(0, 0, 0));
        btnSisDig.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSisDig.setForeground(new java.awt.Color(255, 255, 0));
        btnSisDig.setText("Sistemas Digitales");

        lblAp.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblAp.setForeground(new java.awt.Color(0, 0, 255));
        lblAp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAp.setText("Aprobado");

        lblRp.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblRp.setForeground(new java.awt.Color(255, 0, 0));
        lblRp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRp.setText("Reprobado");

        lblCrs.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblCrs.setForeground(new java.awt.Color(0, 255, 0));
        lblCrs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCrs.setText("Cursando");

        lblNocurs.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblNocurs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNocurs.setText("No cursado");

        lblSemII.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblSemII.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSemII.setText("Semestre II");

        lblSemI.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblSemI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSemI.setText("Semestre I");

        lblSemIII.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblSemIII.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSemIII.setText("Semestre III");

        lblSemIV.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblSemIV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSemIV.setText("Semestre IV");

        btnVolver.setBackground(new java.awt.Color(0, 0, 204));
        btnVolver.setForeground(new java.awt.Color(255, 255, 0));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnQmc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlgI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCalI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSemI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProgAv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnCalII, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlgII, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFsc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSemII, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMatDis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEcDif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCirElc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSisOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSemIII, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnElec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProgObj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSisDig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSemIV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNocurs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAp)
                    .addComponent(lblRp)
                    .addComponent(lblCrs)
                    .addComponent(lblNocurs))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSemII)
                    .addComponent(lblSemIII)
                    .addComponent(lblSemIV)
                    .addComponent(lblSemI))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalI, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalII)
                    .addComponent(btnEcDif)
                    .addComponent(btnElec))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlgI)
                    .addComponent(btnAlgII)
                    .addComponent(btnMatDis)
                    .addComponent(btnEst))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProgAv)
                    .addComponent(btnProgObj)
                    .addComponent(btnCirElc)
                    .addComponent(btnProg))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQmc)
                    .addComponent(btnFsc)
                    .addComponent(btnSisDig)
                    .addComponent(btnSisOp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addContainerGap())
        );

        btnCalI.getAccessibleContext().setAccessibleName("");
        cambioColor(btnCalI);
        cambioColor(btnAlgI);
        cambioColor(btnProg);
        cambioColor(btnQmc);
        cambioColor(btnCalII);
        cambioColor(btnAlgII);
        cambioColor(btnProgAv);
        cambioColor(btnFsc);
        cambioColor(btnMatDis);
        cambioColor(btnSisOp);
        cambioColor(btnCirElc);
        cambioColor(btnEcDif);
        cambioColor(btnElec);
        cambioColor(btnEst);
        cambioColor(btnProgObj);
        cambioColor(btnSisDig);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Opciones op = new Opciones();
        op.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Malla().setVisible(true);
            }
        });
    
    }
    
    public void cambioColor(JButton boton)
    {
        for(int i = 0; i < contAsig; i++){
            if (asigDat[asigAl[i].encontraAsig(asigDat)].getNombre().equalsIgnoreCase(boton.getText()))
            {
                switch(asigAl[i].getSituacion())
                {
                    case "A" :  boton.setBackground(new java.awt.Color(0, 0, 255));
                    break;

                    case "R" :  boton.setBackground(new java.awt.Color(255, 0, 0));
                    break;

                    case "C" :  boton.setBackground(new java.awt.Color(0, 255, 0));
                    break;
                }
            }
        }
    }

    
    @Override
     public void actionPerformed(ActionEvent e) {
        if((e.getSource() == btnCalI) || (e.getSource() == btnAlgI) || (e.getSource() == btnProg) || (e.getSource() == btnQmc)
                 || (e.getSource() == btnCalII) || (e.getSource() == btnAlgII) || (e.getSource() == btnProgAv) || (e.getSource() == btnFsc)
                 || (e.getSource() == btnMatDis) || (e.getSource() == btnSisOp) || (e.getSource() == btnCirElc) || (e.getSource() == btnEcDif)
                 || (e.getSource() == btnElec) || (e.getSource() == btnEst) || (e.getSource() == btnProgObj) || (e.getSource() == btnSisDig))
        {
            JButton a = (JButton) e.getSource(); 
            for(int i = 0; i < contAsig; i++){
                if (asigDat[asigAl[i].encontraAsig(asigDat)].getNombre().equals(a.getText()))
                {
                    posAsigal = i;
                    posAsig = asigAl[i].encontraAsig(asigDat);
                    AsignaturaAlumno asig = new AsignaturaAlumno();
                    asig.setVisible(true);
                    break;
                }  
                else if(i == contAsig - 1)
                {
                    UIManager UI=new UIManager();
                    UI.put("OptionPane.background",new ColorUIResource(255,102,0));
                    UI.put("Panel.background",new ColorUIResource(255,102,0));
                    JOptionPane.showMessageDialog(null, "La asignatura no ha sido cursada", "Error" , JOptionPane.PLAIN_MESSAGE);
                }
             }
        }
    }  
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlgI;
    private javax.swing.JButton btnAlgII;
    private javax.swing.JButton btnCalI;
    private javax.swing.JButton btnCalII;
    private javax.swing.JButton btnCirElc;
    private javax.swing.JButton btnEcDif;
    private javax.swing.JButton btnElec;
    private javax.swing.JButton btnEst;
    private javax.swing.JButton btnFsc;
    private javax.swing.JButton btnMatDis;
    private javax.swing.JButton btnProg;
    private javax.swing.JButton btnProgAv;
    private javax.swing.JButton btnProgObj;
    private javax.swing.JButton btnQmc;
    private javax.swing.JButton btnSisDig;
    private javax.swing.JButton btnSisOp;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAp;
    private javax.swing.JLabel lblCrs;
    private javax.swing.JLabel lblNocurs;
    private javax.swing.JLabel lblRp;
    private javax.swing.JLabel lblSemI;
    private javax.swing.JLabel lblSemII;
    private javax.swing.JLabel lblSemIII;
    private javax.swing.JLabel lblSemIV;
    // End of variables declaration//GEN-END:variables

   
}
