/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import static Codigo.Intranet.asigDat;
import Codigo.LeeFichero;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author PC
 */
public class Mallaño extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Estadistica
     */
    public Mallaño() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtAño = new javax.swing.JTextField();
        lblAño = new javax.swing.JLabel();
        btnCalI = new javax.swing.JButton();
        btnAlgI = new javax.swing.JButton();
        btnProg = new javax.swing.JButton();
        btnQmc = new javax.swing.JButton();
        btnCalII = new javax.swing.JButton();
        btnAlgII = new javax.swing.JButton();
        btnFsc = new javax.swing.JButton();
        btnProgAv = new javax.swing.JButton();
        btnEcDif = new javax.swing.JButton();
        btnMatDis = new javax.swing.JButton();
        btnCirElc = new javax.swing.JButton();
        btnSisOp = new javax.swing.JButton();
        btnElec = new javax.swing.JButton();
        btnEst = new javax.swing.JButton();
        btnProgObj = new javax.swing.JButton();
        btnSisDig = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Malla por Año");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)), "Porcentaje de aprobados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 24))); // NOI18N

        lblAño.setText("Año:");

        btnCalI.addActionListener(this);
        btnCalI.setBackground(new java.awt.Color(0, 0, 255));
        btnCalI.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCalI.setForeground(new java.awt.Color(255, 255, 0));
        btnCalI.setText("Calculo I");

        btnAlgI.addActionListener(this);
        btnAlgI.setBackground(new java.awt.Color(0, 0, 255));
        btnAlgI.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnAlgI.setForeground(new java.awt.Color(255, 255, 0));
        btnAlgI.setText("Algebra I");

        btnProg.addActionListener(this);
        btnProg.setBackground(new java.awt.Color(0, 0, 255));
        btnProg.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnProg.setForeground(new java.awt.Color(255, 255, 0));
        btnProg.setText("Programacion");

        btnQmc.addActionListener(this);
        btnQmc.setBackground(new java.awt.Color(0, 0, 255));
        btnQmc.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnQmc.setForeground(new java.awt.Color(255, 255, 0));
        btnQmc.setText("Quimica");

        btnCalII.addActionListener(this);
        btnCalII.setBackground(new java.awt.Color(0, 0, 255));
        btnCalII.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCalII.setForeground(new java.awt.Color(255, 255, 0));
        btnCalII.setText("Calculo II");

        btnAlgII.addActionListener(this);
        btnAlgII.setBackground(new java.awt.Color(0, 0, 255));
        btnAlgII.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnAlgII.setForeground(new java.awt.Color(255, 255, 0));
        btnAlgII.setText("Algebra II");

        btnFsc.addActionListener(this);
        btnFsc.setBackground(new java.awt.Color(0, 0, 255));
        btnFsc.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnFsc.setForeground(new java.awt.Color(255, 255, 0));
        btnFsc.setText("Fisica");

        btnProgAv.addActionListener(this);
        btnProgAv.setBackground(new java.awt.Color(0, 0, 255));
        btnProgAv.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnProgAv.setForeground(new java.awt.Color(255, 255, 0));
        btnProgAv.setText("Program. Avanzada");

        btnEcDif.addActionListener(this);
        btnEcDif.setBackground(new java.awt.Color(0, 0, 255));
        btnEcDif.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnEcDif.setForeground(new java.awt.Color(255, 255, 0));
        btnEcDif.setText("Ecuaciones Diferenciales");

        btnMatDis.addActionListener(this);
        btnMatDis.setBackground(new java.awt.Color(0, 0, 255));
        btnMatDis.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnMatDis.setForeground(new java.awt.Color(255, 255, 0));
        btnMatDis.setText("Matematicas Discretas");

        btnCirElc.addActionListener(this);
        btnCirElc.setBackground(new java.awt.Color(0, 0, 255));
        btnCirElc.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnCirElc.setForeground(new java.awt.Color(255, 255, 0));
        btnCirElc.setText("Circuitos Electricos");

        btnSisOp.addActionListener(this);
        btnSisOp.setBackground(new java.awt.Color(0, 0, 255));
        btnSisOp.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnSisOp.setForeground(new java.awt.Color(255, 255, 0));
        btnSisOp.setText("Sistemas Operativos");

        btnElec.addActionListener(this);
        btnElec.setBackground(new java.awt.Color(0, 0, 255));
        btnElec.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnElec.setForeground(new java.awt.Color(255, 255, 0));
        btnElec.setText("Electromagnetismo");

        btnEst.addActionListener(this);
        btnEst.setBackground(new java.awt.Color(0, 0, 255));
        btnEst.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnEst.setForeground(new java.awt.Color(255, 255, 0));
        btnEst.setText("Estadisticas");

        btnProgObj.addActionListener(this);
        btnProgObj.setBackground(new java.awt.Color(0, 0, 255));
        btnProgObj.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnProgObj.setForeground(new java.awt.Color(255, 255, 0));
        btnProgObj.setText("Prog. Orientada a Objetos");

        btnSisDig.addActionListener(this);
        btnSisDig.setBackground(new java.awt.Color(0, 0, 255));
        btnSisDig.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnSisDig.setForeground(new java.awt.Color(255, 255, 0));
        btnSisDig.setText("Sistemas Digitales");

        btnVolver.setBackground(new java.awt.Color(0, 0, 204));
        btnVolver.setForeground(new java.awt.Color(255, 255, 0));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblAño)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnQmc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCalI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAlgI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCalII, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAlgII, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFsc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProgAv))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEcDif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMatDis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCirElc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSisOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVolver)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnProgObj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnElec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSisDig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAño))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalI)
                    .addComponent(btnCalII)
                    .addComponent(btnEcDif)
                    .addComponent(btnElec))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlgI)
                    .addComponent(btnAlgII)
                    .addComponent(btnMatDis)
                    .addComponent(btnEst))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProg)
                    .addComponent(btnProgAv)
                    .addComponent(btnCirElc)
                    .addComponent(btnProgObj))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQmc)
                    .addComponent(btnFsc)
                    .addComponent(btnSisOp)
                    .addComponent(btnSisDig))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuEstadisticas menu = new MenuEstadisticas();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mallaño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mallaño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mallaño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mallaño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mallaño().setVisible(true);
            }
        });
    }
    @Override
    public void actionPerformed(ActionEvent e) {
        if((e.getSource() == btnCalI) || (e.getSource() == btnAlgI) || (e.getSource() == btnProg) || (e.getSource() == btnQmc)
                 || (e.getSource() == btnCalII) || (e.getSource() == btnAlgII) || (e.getSource() == btnProgAv) || (e.getSource() == btnFsc)
                 || (e.getSource() == btnMatDis) || (e.getSource() == btnSisOp) || (e.getSource() == btnCirElc) || (e.getSource() == btnEcDif)
                 || (e.getSource() == btnElec) || (e.getSource() == btnEst) || (e.getSource() == btnProgObj) || (e.getSource() == btnSisDig))
        {
            JButton a = (JButton) e.getSource(); 
            for (int i = 0; i < asigDat.length ; i++)
            {
                if(a.getText().equalsIgnoreCase(asigDat[i].getNombre()))
                {
                    UIManager UI=new UIManager();
                    UI.put("OptionPane.background",new ColorUIResource(255,102,0));
                    UI.put("Panel.background",new ColorUIResource(255,102,0));
                    try {
                        JOptionPane.showMessageDialog(null, "El porcentaje de alumnos que aprobaron " + asigDat[i].getNombre() + " el año " +  txtAño.getText() +" son: " + LeeFichero.Alumnoaprob(asigDat[i].getCodigo(), txtAño.getText())+ "%", "Alumnos aprobados" , JOptionPane.PLAIN_MESSAGE);
                    } catch (IOException ex) {
                        Logger.getLogger(Mallaño.class.getName()).log(Level.SEVERE, null, ex);
                    }    
                }    
            }
        }
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlgI;
    private javax.swing.JButton btnAlgII;
    private javax.swing.JButton btnCalI;
    private javax.swing.JButton btnCalII;
    private javax.swing.JButton btnCirElc;
    private javax.swing.JButton btnEcDif;
    private javax.swing.JButton btnElec;
    private javax.swing.JButton btnEst;
    private javax.swing.JButton btnFsc;
    private javax.swing.JButton btnMatDis;
    private javax.swing.JButton btnProg;
    private javax.swing.JButton btnProgAv;
    private javax.swing.JButton btnProgObj;
    private javax.swing.JButton btnQmc;
    private javax.swing.JButton btnSisDig;
    private javax.swing.JButton btnSisOp;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAño;
    private javax.swing.JTextField txtAño;
    // End of variables declaration//GEN-END:variables

    
}
